name: Flask MLProject CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    # Step 4: Start Flask app briefly
    - name: Run Flask app
      run: |
        python app.py &
        sleep 5
        echo " Flask app started successfully"

    # Step 5: Test /predictdata endpoint (GET request)
    - name: Test /predictdata endpoint
      run: |
        python -c "import requests
try:
    resp = requests.get('http://127.0.0.1:5000/predictdata')
    assert resp.status_code == 200
    print(' /predictdata endpoint works')
except Exception as e:
    print(e)
    exit(1)"
